name: pokedex
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  page_transition: ^2.1.0
  path: ^1.9.0
  percent_indicator: ^4.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/
